# Understanding Numpy

In [1]:
import numpy as np

In [2]:
my_list=[1,2,3,4]

In [3]:
arr1=np.array(my_list)

In [4]:
arr1

array([1, 2, 3, 4])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
type(my_matrix)

list

In [7]:
n_2d = np.array(my_matrix) 

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.ones(3, dtype=int)

array([1, 1, 1])

In [11]:
np.full(6,10)

array([10, 10, 10, 10, 10, 10])

In [12]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

## linespace

In [15]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

## eye - to create identity matrix

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## random sampling generation in numpy


In [21]:
from numpy.random import rand, seed


In [20]:
np.random.rand()

0.17792626386806432

In [18]:
rand()

0.6002413385077799

In [24]:
np.random.seed(101)
np.random.rand()

0.5163986277024462

In [25]:
rand(2)

array([0.57066759, 0.02847423])

In [26]:
rand(5,5)

array([[0.17152166, 0.68527698, 0.83389686, 0.30696622, 0.89361308],
       [0.72154386, 0.18993895, 0.55422759, 0.35213195, 0.1818924 ],
       [0.78560176, 0.96548322, 0.23235366, 0.08356143, 0.60354842],
       [0.72899276, 0.27623883, 0.68530633, 0.51786747, 0.04848454],
       [0.13786924, 0.18696743, 0.9943179 , 0.5206654 , 0.57878954]])

### randn:  rand is from a descreet uniform distribution while rand n is from a standard normal distribution, random is from a continuous uniform distribution

In [27]:
np.random.randn(2)

array([0.30266545, 1.69372293])

In [28]:
np.random.randn(2,2)

array([[-1.70608593, -1.15911942],
       [-0.13484072,  0.39052784]])

In [32]:
np.random.random(3)

array([0.52154819, 0.04339669, 0.2239366 ])

In [33]:
np.random.random((3,2))

array([[0.57520509, 0.12043366],
       [0.50011671, 0.13800957],
       [0.0528084 , 0.17827692]])

### random integers

In [29]:
np.random.randint(1,100)

13

In [30]:
np.random.randint(1,100,10)

array([18, 76, 80, 98, 94, 25, 37, 64, 20, 36])

In [31]:
np.random.randint(1,100,size=(3,3))

array([[31, 11, 61],
       [21, 28,  9],
       [87, 27, 88]])

### normal distribution i.e mean of 0 and std of 1 

In [36]:
mu, sigma = 1, 0.1

np.random.normal(mu, sigma, 5)

array([1.10259842, 0.98434021, 0.99684209, 1.06498258, 1.21548464])

In [37]:
np.random.normal(mu, sigma, (3,3))

array([[0.93897411, 0.92446747, 0.96535815],
       [1.01470268, 0.9520552 , 1.05587694],
       [1.10248103, 0.90741257, 1.18628641]])

In [41]:
np.random.uniform(size=(5,2))

array([[0.5296234 , 0.74852037],
       [0.09375686, 0.78452185],
       [0.68724204, 0.6950785 ],
       [0.49686652, 0.97536113],
       [0.20352762, 0.29902041]])

# attributes and methods of array

In [44]:
#arrange
#random
#reshape to turn a 1 dimension array to another dimension

In [46]:
arr= np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [47]:
arr2 = arr.reshape(5,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## checking the dimesion of array

In [49]:
#ndim: this is a method and not a function

arr.ndim


1

In [50]:
arr2.ndim

2

## max , min, armax and armin

In [54]:
arr3 = np.random.randint(1, 50, 10)
arr3

array([21,  1, 48, 30, 12, 41, 28, 46, 34, 25])

In [55]:
arr3.min()

1

In [56]:
arr3.max()

48

In [58]:
#argmin and argmax  argument min shows the index location of minimum and maximum respectively
arr3.argmin()


1

In [59]:
arr3.argmax()

2

### shape is an attribute of the array which return the tuple matrix of the array

In [61]:
arr2.shape

(5, 5)

# array indexing and selection

In [63]:
arr = np.arange(1,10)
arr


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
arr[4]

5

In [65]:
arr[4:9]

array([5, 6, 7, 8, 9])

In [66]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [67]:
arr[2::4]

array([3, 7])

In [68]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [69]:
arr[:-3]

array([1, 2, 3, 4, 5, 6])

## broadcast

In [70]:
arr[0:5]=100

In [71]:
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9])

In [73]:
slice_of_arr = arr[0:6]
slice_of_arr

array([100, 100, 100, 100, 100,   6])

In [74]:
slice_of_arr[:]=50

In [75]:
slice_of_arr

array([50, 50, 50, 50, 50, 50])

In [76]:
arr

array([50, 50, 50, 50, 50, 50,  7,  8,  9])

In [78]:
arr_copy = arr.copy()
arr.copy

<function ndarray.copy>

In [80]:
arr_copy

array([50, 50, 50, 50, 50, 50,  7,  8,  9])

In [81]:
arr_copy[1:5]= 30

In [82]:
arr_copy

array([50, 30, 30, 30, 30, 50,  7,  8,  9])

In [83]:
arr

array([50, 50, 50, 50, 50, 50,  7,  8,  9])

### indexing a two dimensional array

In [85]:
arr_2d = np.array(([5,10,15],[20,35,40],[40,20,10]))

In [86]:
arr_2d

array([[ 5, 10, 15],
       [20, 35, 40],
       [40, 20, 10]])

In [87]:
arr_2d[1]

array([20, 35, 40])

In [90]:
arr_2d[1][1]   #to grab data from a 2d array [row][column],[row,column]

35

In [91]:
arr_2d[1,1]

35

In [93]:
arr_2d[0:2,1:]       # to get out a matrix from a matrix

array([[10, 15],
       [35, 40]])