# Fancy Indexing

In [38]:
import numpy as np

In [39]:
arr2d = np.zeros((10,10))

In [40]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [41]:
#lenght of array

arr_length = arr2d.shape[1]

In [42]:
for i in range(arr_length):
    arr2d[i]=i

In [43]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [44]:
arr2d[[2,3]]   #fancy array can only be used for rows

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

In [45]:
arr2d[[2,9,7]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## conditional selection of array  

< > <= => == !=

for multiple selection it involves AND(&) OR(|)

In [46]:
arry = np.arange(1,11)

In [47]:
arry

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arry >4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [49]:
arry[arry>4]

array([ 5,  6,  7,  8,  9, 10])

### two dimensioanl array conditional selection

In [50]:
np.random.seed(101)

heights = np.random.uniform(50,150,size=10)

heights

array([101.63986277, 107.06675869,  52.84742265,  67.15216562,
       118.52769817, 133.38968626,  80.69662197, 139.36130797,
       122.15438618,  68.99389542])

In [51]:
heights[heights>100]

array([101.63986277, 107.06675869, 118.52769817, 133.38968626,
       139.36130797, 122.15438618])

In [52]:
np.where(heights>100)

(array([0, 1, 4, 5, 7, 8], dtype=int64),)

In [53]:
np.where(heights>100, True, False)

array([ True,  True, False, False,  True,  True, False,  True,  True,
       False])

In [54]:
heights[np.where(heights>100)]

array([101.63986277, 107.06675869, 118.52769817, 133.38968626,
       139.36130797, 122.15438618])

In [55]:
np.random.seed(101)

heights = np.random.uniform(50,150,size=25)

heights1 = heights.reshape(5,5)

In [56]:
heights1.shape

(5, 5)

In [57]:
heights1

array([[101.63986277, 107.06675869,  52.84742265,  67.15216562,
        118.52769817],
       [133.38968626,  80.69662197, 139.36130797, 122.15438618,
         68.99389542],
       [105.42275911,  85.2131954 ,  68.18924027, 128.56017619,
        146.54832224],
       [ 73.23536618,  58.35614337, 110.35484223, 122.89927573,
         77.62388285],
       [118.53063288, 101.78674742,  54.84845374,  63.78692376,
         68.69674261]])

In [58]:
(heights1<60) & (heights1>100)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [59]:
heights1[np.where((heights1>60) & (heights1<100))]   #always add brackets to avoid ambigious error 

array([67.15216562, 80.69662197, 68.99389542, 85.2131954 , 68.18924027,
       73.23536618, 77.62388285, 63.78692376, 68.69674261])

### iterating over array

In [60]:
heights1

array([[101.63986277, 107.06675869,  52.84742265,  67.15216562,
        118.52769817],
       [133.38968626,  80.69662197, 139.36130797, 122.15438618,
         68.99389542],
       [105.42275911,  85.2131954 ,  68.18924027, 128.56017619,
        146.54832224],
       [ 73.23536618,  58.35614337, 110.35484223, 122.89927573,
         77.62388285],
       [118.53063288, 101.78674742,  54.84845374,  63.78692376,
         68.69674261]])

In [61]:
for i in heights:
    print(i)

101.63986277024462
107.06675868681398
52.847422647809694
67.15216562251031
118.52769816973125
133.38968626360764
80.69662196722378
139.36130796833973
122.15438617683047
68.99389542047967
105.42275911247872
85.21319540266141
68.18924026600787
128.56017618643588
146.54832224119693
73.23536618147607
58.356143366334365
110.35484222912186
122.89927572876178
77.62388284972627
118.53063287801783
101.78674741970474
54.84845374264006
63.78692375621061
68.69674261379211


In [62]:
# to print out values in a 2 dimensional aerray use a nested for loop

for i in heights1:
    for j in i:
        print(j)

101.63986277024462
107.06675868681398
52.847422647809694
67.15216562251031
118.52769816973125
133.38968626360764
80.69662196722378
139.36130796833973
122.15438617683047
68.99389542047967
105.42275911247872
85.21319540266141
68.18924026600787
128.56017618643588
146.54832224119693
73.23536618147607
58.356143366334365
110.35484222912186
122.89927572876178
77.62388284972627
118.53063287801783
101.78674741970474
54.84845374264006
63.78692375621061
68.69674261379211


In [63]:
for i in np.nditer(heights1):    #single line of code to help with the forloop optimizing time and process
    print(i)

101.63986277024462
107.06675868681398
52.847422647809694
67.15216562251031
118.52769816973125
133.38968626360764
80.69662196722378
139.36130796833973
122.15438617683047
68.99389542047967
105.42275911247872
85.21319540266141
68.18924026600787
128.56017618643588
146.54832224119693
73.23536618147607
58.356143366334365
110.35484222912186
122.89927572876178
77.62388284972627
118.53063287801783
101.78674741970474
54.84845374264006
63.78692375621061
68.69674261379211


# numpy operations

### arithmetic

In [64]:
arr = np.arange(0,10)

In [65]:
 arr1 = arr + arr
arr1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [66]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [67]:
arr1 - arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
arr1/ arr

C:\Users\ORISA\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.])

In [69]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [70]:
arr % 3

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0], dtype=int32)

In [71]:
arr2 = np.arange(0,12)

### universal operation

In [72]:
arr1d = np.random.normal(3,0.5,(5,5))
arr1d

array([[3.00429152, 3.10265351, 3.79458784, 3.26661042, 3.42867462],
       [3.04353816, 2.80126914, 3.63084399, 3.21666566, 2.93169315],
       [3.44106992, 2.81109438, 3.0733194 , 3.63456089, 3.15394054],
       [2.69659723, 3.45965921, 2.4019408 , 3.25447261, 2.57578002],
       [4.00539673, 2.93119515, 2.70086539, 3.01411687, 3.19637304]])

In [73]:
np.mean(arr1d)    

3.1428484074555456

In [74]:
np.mean(arr1d, axis=1)        #column = 1, row =0  rowXcolumn

array([3.31936358, 3.12480202, 3.22279703, 2.87768997, 3.16958944])

In [75]:
np.std(arr1d)

0.37889804556721146

In [76]:
np.var(arr1d)

0.14356372893465263

In [77]:
np.sum(arr1d)

78.57121018638864

In [78]:
np.cumsum(arr1d)

array([ 3.00429152,  6.10694503,  9.90153288, 13.16814329, 16.59681791,
       19.64035608, 22.44162522, 26.07246921, 29.28913487, 32.22082802,
       35.66189794, 38.47299232, 41.54631171, 45.18087261, 48.33481315,
       51.03141037, 54.49106958, 56.89301038, 60.14748299, 62.72326301,
       66.72865974, 69.65985489, 72.36072028, 75.37483715, 78.57121019])

In [79]:
arr1d.sum()        #python automatical sees the variable as a numpy array so yopou can use the operators as methods

78.57121018638864

In [80]:
np.sqrt(arr1d)

array([[1.73328922, 1.76143507, 1.94797019, 1.80737667, 1.85166806],
       [1.74457392, 1.67369924, 1.90547737, 1.79350653, 1.71221878],
       [1.85501211, 1.67663186, 1.75308853, 1.90645244, 1.77593371],
       [1.64213192, 1.86001592, 1.5498196 , 1.80401569, 1.60492368],
       [2.00134873, 1.71207335, 1.64343098, 1.73612121, 1.78784033]])

In [81]:
np.cos(arr1d)

array([[-0.990589  , -0.99924197, -0.79426758, -0.99219545, -0.95907421],
       [-0.99519651, -0.94264673, -0.88268495, -0.99718335, -0.97805186],
       [-0.95549084, -0.94588076, -0.99767029, -0.88093204, -0.99992377],
       [-0.90261263, -0.94984184, -0.73870326, -0.99363582, -0.84415322],
       [-0.64954986, -0.97794797, -0.90444165, -0.99188596, -0.99849993]])

In [82]:
a = np.log(arr1d)
a

array([[1.10004177, 1.13225772, 1.3335758 , 1.18375288, 1.23217378],
       [1.11302071, 1.03007258, 1.28946513, 1.16834531, 1.07558012],
       [1.23578245, 1.03357387, 1.12275821, 1.2904883 , 1.14865264],
       [0.99199069, 1.24117009, 0.87627708, 1.18003024, 0.94615241],
       [1.38764263, 1.07541024, 0.99357224, 1.10330688, 1.16201674]])

In [83]:
a.mean()

1.1378844197717009

# #

# Pandas

## Series

In [84]:
import numpy as np
import pandas as pd          #pandas can hold any data type

In [85]:
Label = ['a','b','c','d']
my_list = [10,20,30,40]
arr = np.array([10,20,30,40])
my_dict= {'a':10,'b':20,'c':30,'d':40}

In [86]:
pd.Series(data=my_list,index=Label)  # or pd.Series(my_list,Label)

a    10
b    20
c    30
d    40
dtype: int64

In [87]:
# creating serires with an array

ser = pd.Series(data=arr,index=Label)
ser

a    10
b    20
c    30
d    40
dtype: int32

In [88]:
# creating series from a dictionary

ser = pd.Series(my_dict)
ser

a    10
b    20
c    30
d    40
dtype: int64

In [89]:
ser1 = pd.Series([15,23,31,45],['US','Germany','Nigeria','Japan']) 
ser1

US         15
Germany    23
Nigeria    31
Japan      45
dtype: int64

In [90]:
ser2 = pd.Series([15.2,23.5,31,45.2],['US','Germany','Nigeria','Italy'])
ser2

US         15.2
Germany    23.5
Nigeria    31.0
Italy      45.2
dtype: float64

In [91]:
ser1[2:3]

Nigeria    31
dtype: int64

## Series operations

### all operations perfromed on numpy can also be performed on series

In [92]:
ser1+ser2

Germany    46.5
Italy       NaN
Japan       NaN
Nigeria    62.0
US         30.2
dtype: float64

## DataFrame

In [93]:
from numpy.random import randn
from numpy.random import seed

In [94]:
seed(101)
sdata = randn(5,4)
sdata

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [95]:
df = pd.DataFrame(sdata,index=['A','B','C','D','E'],columns=['G1','G2','G3','G4'])
df

G1        G2        G3        G4
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [96]:
pd.DataFrame(sdata,(range(0,5)),['a','b','c','d'])

a         b         c         d
0  2.706850  0.628133  0.907969  0.503826
1  0.651118 -0.319318 -0.848077  0.605965
2 -2.018168  0.740122  0.528813 -0.589001
3  0.188695 -0.758872 -0.933237  0.955057
4  0.190794  1.978757  2.605967  0.683509

### selection and indexing via COLUMNS

In [97]:
type(df)

pandas.core.frame.DataFrame

In [98]:
df['G1']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: G1, dtype: float64

In [99]:
df['G1']+df['G4']

A    3.210676
B    1.257083
C   -2.607169
D    1.143752
E    0.874303
dtype: float64

In [100]:
df.G1

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: G1, dtype: float64

In [101]:
df[['G1','G4']]

G1        G4
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [102]:
# creating new columns within dataframe

df['G5']=randn(5)
df

G1        G2        G3        G4        G5
A  2.706850  0.628133  0.907969  0.503826  0.302665
B  0.651118 -0.319318 -0.848077  0.605965  1.693723
C -2.018168  0.740122  0.528813 -0.589001 -1.706086
D  0.188695 -0.758872 -0.933237  0.955057 -1.159119
E  0.190794  1.978757  2.605967  0.683509 -0.134841

In [103]:
df['G6'] = df['G3']+df['G5']

In [104]:
df

G1        G2        G3        G4        G5        G6
A  2.706850  0.628133  0.907969  0.503826  0.302665  1.210635
B  0.651118 -0.319318 -0.848077  0.605965  1.693723  0.845646
C -2.018168  0.740122  0.528813 -0.589001 -1.706086 -1.177272
D  0.188695 -0.758872 -0.933237  0.955057 -1.159119 -2.092357
E  0.190794  1.978757  2.605967  0.683509 -0.134841  2.471127

### Removing Columns



In [105]:
df.drop('G3', axis=1, inplace=True)     # inplace argument drops the column permenetly 

In [106]:
df


G1        G2        G4        G5        G6
A  2.706850  0.628133  0.503826  0.302665  1.210635
B  0.651118 -0.319318  0.605965  1.693723  0.845646
C -2.018168  0.740122 -0.589001 -1.706086 -1.177272
D  0.188695 -0.758872  0.955057 -1.159119 -2.092357
E  0.190794  1.978757  0.683509 -0.134841  2.471127

In [107]:
df.drop(['G4','G1'], axis=1)            # dropping multiple columns

G2        G5        G6
A  0.628133  0.302665  1.210635
B -0.319318  1.693723  0.845646
C  0.740122 -1.706086 -1.177272
D -0.758872 -1.159119 -2.092357
E  1.978757 -0.134841  2.471127

In [108]:
df

G1        G2        G4        G5        G6
A  2.706850  0.628133  0.503826  0.302665  1.210635
B  0.651118 -0.319318  0.605965  1.693723  0.845646
C -2.018168  0.740122 -0.589001 -1.706086 -1.177272
D  0.188695 -0.758872  0.955057 -1.159119 -2.092357
E  0.190794  1.978757  0.683509 -0.134841  2.471127

In [109]:
df


G1        G2        G4        G5        G6
A  2.706850  0.628133  0.503826  0.302665  1.210635
B  0.651118 -0.319318  0.605965  1.693723  0.845646
C -2.018168  0.740122 -0.589001 -1.706086 -1.177272
D  0.188695 -0.758872  0.955057 -1.159119 -2.092357
E  0.190794  1.978757  0.683509 -0.134841  2.471127

## Selecting rows

In [110]:
#index by location

df.loc['B']

G1    0.651118
G2   -0.319318
G4    0.605965
G5    1.693723
G6    0.845646
Name: B, dtype: float64

In [111]:
#indexing by index location(iloc)

df.iloc[1]

G1    0.651118
G2   -0.319318
G4    0.605965
G5    1.693723
G6    0.845646
Name: B, dtype: float64

In [112]:
df.loc[['A','B']]

G1        G2        G4        G5        G6
A  2.706850  0.628133  0.503826  0.302665  1.210635
B  0.651118 -0.319318  0.605965  1.693723  0.845646

In [114]:
df.loc[['A','B'],['G1','G5']]

G1        G5
A  2.706850  0.302665
B  0.651118  1.693723

### Conditional selection

In [115]:
df > 0

G1     G2     G4     G5     G6
A   True   True   True   True   True
B   True  False   True   True   True
C  False   True  False  False  False
D   True  False   True  False  False
E   True   True   True  False   True

In [116]:
df[df>0]

G1        G2        G4        G5        G6
A  2.706850  0.628133  0.503826  0.302665  1.210635
B  0.651118       NaN  0.605965  1.693723  0.845646
C       NaN  0.740122       NaN       NaN       NaN
D  0.188695       NaN  0.955057       NaN       NaN
E  0.190794  1.978757  0.683509       NaN  2.471127

In [117]:
df[df['G2']>0]

G1        G2        G4        G5        G6
A  2.706850  0.628133  0.503826  0.302665  1.210635
C -2.018168  0.740122 -0.589001 -1.706086 -1.177272
E  0.190794  1.978757  0.683509 -0.134841  2.471127

In [119]:
df[df['G1']>0][['G4','G2']]

G4        G2
A  0.503826  0.628133
B  0.605965 -0.319318
D  0.955057 -0.758872
E  0.683509  1.978757

In [124]:
df[(df['G1']>0) & (df['G4']>1)]

Empty DataFrame
Columns: [G1, G2, G4, G5, G6]
Index: []

### Reseting index to default index

In [125]:
df.reset_index()     #to make it permanet put the inplace=True arguuement

index        G1        G2        G4        G5        G6
0     A  2.706850  0.628133  0.503826  0.302665  1.210635
1     B  0.651118 -0.319318  0.605965  1.693723  0.845646
2     C -2.018168  0.740122 -0.589001 -1.706086 -1.177272
3     D  0.188695 -0.758872  0.955057 -1.159119 -2.092357
4     E  0.190794  1.978757  0.683509 -0.134841  2.471127

### Changing Index / setting index

In [126]:
df['States']=['Abj','Ekt','Akr','Oyo','Abk']

In [129]:
newid = 'Abj Ekt Akr Oyo Abk'.split()
newid

['Abj', 'Ekt', 'Akr', 'Oyo', 'Abk']

In [131]:
df['states1']=newid

In [132]:
df

G1        G2        G4        G5        G6 States states1
A  2.706850  0.628133  0.503826  0.302665  1.210635    Abj     Abj
B  0.651118 -0.319318  0.605965  1.693723  0.845646    Ekt     Ekt
C -2.018168  0.740122 -0.589001 -1.706086 -1.177272    Akr     Akr
D  0.188695 -0.758872  0.955057 -1.159119 -2.092357    Oyo     Oyo
E  0.190794  1.978757  0.683509 -0.134841  2.471127    Abk     Abk

In [134]:
df.set_index('states1')

G1        G2        G4        G5        G6 States
states1                                                         
Abj      2.706850  0.628133  0.503826  0.302665  1.210635    Abj
Ekt      0.651118 -0.319318  0.605965  1.693723  0.845646    Ekt
Akr     -2.018168  0.740122 -0.589001 -1.706086 -1.177272    Akr
Oyo      0.188695 -0.758872  0.955057 -1.159119 -2.092357    Oyo
Abk      0.190794  1.978757  0.683509 -0.134841  2.471127    Abk

In [127]:
df.set_index('States')

G1        G2        G4        G5        G6
States                                                  
Abj     2.706850  0.628133  0.503826  0.302665  1.210635
Ekt     0.651118 -0.319318  0.605965  1.693723  0.845646
Akr    -2.018168  0.740122 -0.589001 -1.706086 -1.177272
Oyo     0.188695 -0.758872  0.955057 -1.159119 -2.092357
Abk     0.190794  1.978757  0.683509 -0.134841  2.471127

### multi level index dataframe

In [135]:
#index levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
h_index=list(zip(outside,inside))
h_index

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [137]:
zip(outside,inside)

In [136]:
h_index = pd.MultiIndex.from_tuples(h_index)
h_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [141]:
df = pd.DataFrame(np.random.randn(6,2),index=h_index,columns=('A','B'))

In [142]:
df


A         B
G1 1  2.084019 -0.376519
   2  0.230336  0.681209
   3  1.035125 -0.031160
G2 1  1.939932 -1.005187
   2 -0.741790  0.187125
   3 -0.732845 -1.382920

In [143]:
np.random.randn(6,2)

array([[ 1.4824955 ,  0.96145816],
       [-2.14121229,  0.99257345],
       [ 1.19224064, -1.04677954],
       [ 1.29276458, -1.46751402],
       [-0.49409536, -0.16253473],
       [ 0.48580874,  0.39248881]])

In [144]:
#indexing out of a multi indexing

df.loc['G1'].loc[2]

A    0.230336
B    0.681209
Name: 2, dtype: float64

In [152]:
df.loc['G1'].loc[2]['A']  # no need for loc when picking from the column

0.23033634359240704

In [145]:
df.loc['G1']

A         B
1  2.084019 -0.376519
2  0.230336  0.681209
3  1.035125 -0.031160

In [146]:
df.index.names=['Group','levels']

In [147]:
df

A         B
Group levels                    
G1    1       2.084019 -0.376519
      2       0.230336  0.681209
      3       1.035125 -0.031160
G2    1       1.939932 -1.005187
      2      -0.741790  0.187125
      3      -0.732845 -1.382920

### cross sectional indexing and it works only for multi level indexing

In [150]:
df.xs('G1')

A         B
levels                    
1       2.084019 -0.376519
2       0.230336  0.681209
3       1.035125 -0.031160

In [149]:
df.xs(['G1',1])

A    2.084019
B   -0.376519
Name: (G1, 1), dtype: float64

## Groupby

In [174]:
#create dataframe
columnss = ['Company','Person','Sales']
person =[['GOOG','sam',200],['GOOG','Charlie',120],['MSFT','Amy',340],['MSFT','Vanessa',124],['FB','Carl',243],['FB','Sarah',350]]

In [175]:
person

[['GOOG', 'sam', 200],
 ['GOOG', 'Charlie', 120],
 ['MSFT', 'Amy', 340],
 ['MSFT', 'Vanessa', 124],
 ['FB', 'Carl', 243],
 ['FB', 'Sarah', 350]]

In [176]:
df = pd.DataFrame(person,columns=columnss)
df

Company   Person  Sales
0    GOOG      sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [177]:
df_groupby = df.groupby('Company')
df_groupby2 = df.groupby('Sales')

In [178]:
df_groupby.mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

In [179]:
df_groupby.sum()

Sales
Company       
FB         593
GOOG       320
MSFT       464

In [180]:
df_groupby.describe()

Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [181]:
df_groupby.describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

In [184]:
df_groupby2.count()

Company  Person
Sales                 
120          1       1
124          1       1
200          1       1
243          1       1
340          1       1
350          1       1

## Missing Data


In [185]:
df = pd.DataFrame({'A':[1,2,np.nan],
                   'B':[5,np.nan,7],
                   'C':[3,6,1]})

In [186]:
df


A    B  C
0  1.0  5.0  3
1  2.0  NaN  6
2  NaN  7.0  1

In [188]:
#dropping missing values: drop missing values only when the mean is no longer a measure of tendency or if the missing value
#are much in population

df.dropna() # this involves droping pairwisely i.e dropping the whole row of the missing data, put axis = 1 
#in argument to drop in columns

A    B  C
0  1.0  5.0  3

In [189]:
df.dropna(axis=1)

C
0  3
1  6
2  1

In [191]:
df.dropna(thresh=2, axis=1)  #the thresh arguement is to drop the column that contains the number of thresh given

A    B  C
0  1.0  5.0  3
1  2.0  NaN  6
2  NaN  7.0  1

In [192]:
#replacing missing claues

df.fillna(value='Fill  Value')

A            B  C
0            1            5  3
1            2  Fill  Value  6
2  Fill  Value            7  1

In [194]:
df.fillna(df.mean())     #calculates the mean by column and fills it by the mean

A    B  C
0  1.0  5.0  3
1  2.0  6.0  6
2  1.5  7.0  1

In [195]:
df.fillna(df['A'].mean())

A    B  C
0  1.0  5.0  3
1  2.0  1.5  6
2  1.5  7.0  1

## Pandas Operations

In [198]:
df = pd.DataFrame({'col':[1,2,3,4,5,6,7,8,9,10],'col2':[444,111,222,333,999,666,888,555,666,777],'col3':['abc','qwe','asd','ghj','fgc','awe','ghd','gsa','tyu','qaz']})

In [199]:
df

col  col2 col3
0    1   444  abc
1    2   111  qwe
2    3   222  asd
3    4   333  ghj
4    5   999  fgc
5    6   666  awe
6    7   888  ghd
7    8   555  gsa
8    9   666  tyu
9   10   777  qaz

In [200]:
df.head()

col  col2 col3
0    1   444  abc
1    2   111  qwe
2    3   222  asd
3    4   333  ghj
4    5   999  fgc

In [201]:
df.tail()

col  col2 col3
5    6   666  awe
6    7   888  ghd
7    8   555  gsa
8    9   666  tyu
9   10   777  qaz

In [203]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
col     10 non-null int64
col2    10 non-null int64
col3    10 non-null object
dtypes: int64(2), object(1)
memory usage: 368.0+ bytes


In [205]:
df.isnull()   #to know number of missing data

col   col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
5  False  False  False
6  False  False  False
7  False  False  False
8  False  False  False
9  False  False  False

In [206]:
df.isnull().sum()

col     0
col2    0
col3    0
dtype: int64

In [207]:
# checking for unique values; to heck if there are same values in the data

df['col2'].unique()

array([444, 111, 222, 333, 999, 666, 888, 555, 777], dtype=int64)

In [208]:
df['col2'].nunique()

9

In [210]:
#### checking for unique value count

df['col2'].value_counts()

666    2
111    1
222    1
333    1
444    1
555    1
777    1
888    1
999    1
Name: col2, dtype: int64

In [211]:
# getting attributes of the data frame

df.columns

Index(['col', 'col2', 'col3'], dtype='object')

In [212]:
df.sort_values('col2')

col  col2 col3
1    2   111  qwe
2    3   222  asd
3    4   333  ghj
0    1   444  abc
7    8   555  gsa
5    6   666  awe
8    9   666  tyu
9   10   777  qaz
6    7   888  ghd
4    5   999  fgc

In [215]:
# selecting data based on a criteria

df[(df['col']>2) & (df['col2']<555)]

col  col2 col3
2    3   222  asd
3    4   333  ghj

### applying a function to your dataframe



In [221]:
def times2(x):
    return x**2

In [222]:
df['col'] = df['col'].apply(times2)

In [223]:
df

col  col2 col3
0    1   444  abc
1    4   111  qwe
2    9   222  asd
3   16   333  ghj
4   25   999  fgc
5   36   666  awe
6   49   888  ghd
7   64   555  gsa
8   81   666  tyu
9  100   777  qaz

In [229]:
units = lambda x : x//100

In [230]:
df['col2']=df['col2'].apply(units)

In [231]:
df

col  col2 col3
0    1     4  abc
1    4     1  qwe
2    9     2  asd
3   16     3  ghj
4   25     9  fgc
5   36     6  awe
6   49     8  ghd
7   64     5  gsa
8   81     6  tyu
9  100     7  qaz

In [232]:
# removing a row or column permanently

del df['col']

In [234]:
df

col2 col3
0     4  abc
1     1  qwe
2     2  asd
3     3  ghj
4     9  fgc
5     6  awe
6     8  ghd
7     5  gsa
8     6  tyu
9     7  qaz

## Pivot Tables

In [235]:
data = {'A':['food','food','food','bar','bar','bar'],
       'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)

In [236]:
df

A    B  C  D
0  food  one  x  1
1  food  one  y  3
2  food  two  x  2
3   bar  two  y  5
4   bar  one  x  4
5   bar  one  y  1

In [239]:
dpivot = df.pivot_table(values='D',index=['A','B'], columns =['C'])

In [242]:
dpivot.index

MultiIndex([( 'bar', 'one'),
            ( 'bar', 'two'),
            ('food', 'one'),
            ('food', 'two')],
           names=['A', 'B'])

In [243]:
dpivot

C           x    y
A    B            
bar  one  4.0  1.0
     two  NaN  5.0
food one  1.0  3.0
     two  2.0  NaN